import type { Metadata } from "next";
import { Noto_Serif_Display, Noto_Serif } from "next/font/google";
import "@/_styles/globals.css";
import { Header } from "@/_components/navigation/header/header";
import { Footer } from "@/_components/navigation/footer/footer";

const notoSerifDisplay = Noto_Serif_Display({
  subsets: ["latin"],
});

const notoSerif = Noto_Serif({
  subsets: ["latin"],
  weight: ["200"],
});

export const metadata: Metadata = {
  title: "Big Day Event",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSerifDisplay} ${notoSerif} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
